---
namespace: iamgini
name: demo_colelction_roles_modules
version: 1.1.0
readme: README.md
authors:
  - Gineesh Madapparambath <gini@iamgini.com>
description: Ansible Collection with custom Module Demos
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - demos
  - ansible
  - devops
dependencies: {}
repository: https://github.com/iamgini/ansible-collection-demo-roles-modules
documentation: https://github.com/iamgini/ansible-collection-demo-roles-modules
homepage: https://github.com/iamgini/ansible-collection-demo-roles-modules
issues: https://github.com/iamgini/ansible-collection-demo-roles-modules/issues

#build_ignore:
#- .gitignore
#- changelogs/.plugin-cache.yaml
