---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    tag: ''
    collection_namespace: "{{ (lookup('file','../galaxy.yml') | from_yaml).namespace }}"
    collection_name: "{{ (lookup('file','../galaxy.yml') | from_yaml).name }}"

    # input the private automation hub url
    # server: private automation hub 
    # eg: https://automationhub22-1.lab.local/api/galaxy/content/published/

  tasks:

    # - name: Ensure the ANSIBLE_GALAXY_TOKEN environment variable is set.
    #   fail:
    #     msg: ANSIBLE_GALAXY_TOKEN is not set.
    #   when: "lookup('env','ANSIBLE_GALAXY_TOKEN') == ''"

    - name: Set API server
      ansible.builtin.set_fact:
        galaxy_api_server: "--server {{ server }}"
      when: server is defined

    - name: Templating galaxy.yml file.
      template:
        src: templates/galaxy.yaml.j2
        dest: ../galaxy.yml

    - name: Build the collection.
      command: >
        ansible-galaxy collection build --force
        chdir=../
    - name: Publish the collection.
      command: >
        ansible-galaxy collection publish ./{{ collection_namespace }}-{{ collection_name }}-{{ tag }}.tar.gz --api-key $ANSIBLE_GALAXY_TOKEN --ignore-certs {{ galaxy_api_server | default('') }}
        chdir=../
      register: galaxy_publish_status
    - name: Galaxy Publish Status
      debug:
        msg: "{{ galaxy_publish_status }}"
        
    - name: Remove Archive file
      ansible.builtin.file:
        path: ./{{ collection_namespace }}-{{ collection_name }}-{{ tag }}.tar.gz
        state: absent